version: '3.8'

services:

  stormcloud-sst:
    container_name: stormcloud-sst
    build:
      context: .
      dockerfile: Dockerfile.sst
    env_file:
      - ./stormcloud/plugins/sst/.env

  stormcloud-temp-precip:
    container_name: stormcloud-temp-precip
    build:
      context: .
      dockerfile: Dockerfile.temp_precip
    env_file:
      - ./stormcloud/plugins/temp_precip/.env

  stormcloud-doc-rank:
    container_name: stormcloud-doc-rank
    build:
      context: .
      dockerfile: Dockerfile.doc_rank
    env_file:
      - ./stormcloud/plugins/doc_rank/.env

  # stormcloud-etl-transpose-geom:
  #   container_name: stormcloud-transpose-geom
  #   build:
  #     dockerfile: Dockerfile.transpose_geom
  #   env_file:
  #     - ./stormcloud/etl/transpose_geom/.env
  #   tty: true

  # stormcloud-etl-create-ranked-grid:
  #   container_name: stormcloud-create-ranked-grid
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.create_ranked_grid
  #   env_file:
  #     - ./stormcloud/etl/create_ranked_grid/.env
  #   tty: true
