version: '3.8'

services:

  stormcloud-sst:
    container_name: stormcloud-sst
    build:
      dockerfile: Dockerfile.sst
    env_file:
      - ./.env

  stormcloud-temp-precip:
    container_name: stormcloud-temp-precip
    build:
      dockerfile: Dockerfile.temp_precip
    env_file:
      - ./.env

  stormcloud-etl-temp-transfer:
    container_name: stormcloud-temp-transfer
    build:
      dockerfile: Dockerfile.temp_transfer
    env_file:
      - ./.env
    tty: true

  stormcloud-etl-top-storms-dss:
    container_name: stormcloud-top-storms-dss
    build:
      dockerfile: Dockerfile.top_storms_dss
    env_file:
      - ./.env
    tty: true