version: '3.8'

services:

  stormcloud-sst:
    container_name: stormcloud-sst
    build:
      context: .
      dockerfile: Dockerfile.sst
    env_file:
      - ./stormcloud/plugins/sst/.env

  stormcloud-temp-precip:
    container_name: stormcloud-temp-precip
    build:
      context: .
      dockerfile: Dockerfile.temp_precip
    env_file:
      - ./stormcloud/plugins/temp_precip/.env

  # stormcloud-etl-temp-transfer:
  #   container_name: stormcloud-temp-transfer
  #   build:
  #     dockerfile: Dockerfile.temp_transfer
  #   env_file:
  #     - ./stormcloud/etl/temp_transfer/.env
  #   tty: true

  # stormcloud-etl-top-storms-dss:
  #   container_name: stormcloud-top-storms-dss
  #   build:
  #     dockerfile: Dockerfile.top_storms_dss
  #   env_file:
  #     - ./stormcloud/etl/top_storms/.env
  #   tty: true

  # stormcloud-etl-transpose-geom:
  #   container_name: stormcloud-transpose-geom
  #   build:
  #     dockerfile: Dockerfile.transpose_geom
  #   env_file:
  #     - ./stormcloud/etl/transpose_geom/.env
  #   tty: true