version: '3.8'

services:

  stormcloud-sst:
    container_name: stormcloud-sst
    build:
      context: .
    env_file:
      - ./.env

  stormcloud-temp-precip:
    container_name: stormcloud-temp-precip
    build:
      context: .
    env_file:
      - ./.env