name: stormcloud-ci
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build-container:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set date env
        run: echo "DATETAG=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/${{ secrets.ECR_ROLE_NAME }}
          role-session-name: updateimage
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            sst:
              - 'stormcloud/plugins/sst/**'
            temp_precip:
              - 'stormcloud/plugins/temp_precip/**'

      # run only if 'sst' files are modified
      - name: Build, tag, and push client docker image to Amazon ECR
        if: steps.filter.outputs.sst == 'true'
        run: |
          docker build ./client --target prod -t ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:sst-${{github.sha }} 
          docker push ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:sst-${{ github.sha }}
          docker tag ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:sst-${{ github.sha }} ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:sst-latest
          docker push ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:sst-latest

      # run only if 'temp_precip' files are modified
      - name: Build, tag, and push API docker image to Amazon ECR
        if: steps.filter.outputs.temp_precip == 'true'
        run: |
          docker build ./api --target prod -t ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:temp_precip-${{ github.sha }}
          docker push ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:temp_precip-${{ github.sha}}
          docker tag ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:temp_precip-${{ github.sha }} ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:temp_precip-latest
          docker push ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/stormcloud:temp_precip-latest